// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Identifier = {__proto__:null,slice:10, rm:20, ui:34, cmd:40, evt:46, exc:52, aut:56, ext:60, data:72, true:88, false:90, null:92}
export const parser = LRParser.deserialize({
  version: 14,
  states: "+^QVQPOOOzQPO'#C{OOQO'#Cd'#CdO!PQPO'#CcOOQO'#C^'#C^OOQO'#D^'#D^QVQPOOO!zQPO'#C_O#PQPO'#CeO#UQPO'#ClO#ZQPO'#CoO#`QPO'#CrO#eQPO'#CuO#jQPO'#CwO#oQPO'#CyO#tQPO'#DPO#yQPO,59gO$OQPO'#C|OOQO,58},58}OOQO-E7[-E7[OOQO,58y,58yO$jQPO,59PO$oQPO,59WO$tQPO,59ZO$yQPO,59^O%OQPO,59aO%TQPO,59cO%YQPO,59eO%_QPO,59kO&YQPO1G/RO'ZQPO,59hOOQO'#Ch'#ChO(UQPO1G.kOOQO'#Cn'#CnO)VQPO1G.rOOQO'#Cq'#CqO*WQPO1G.uOOQO'#Ct'#CtO+XQPO1G.xO,YQPO1G.{O-ZQPO1G.}O.[QPO1G/PO/]QPO'#DROOQO1G/V1G/VO/hQPO'#CiOOQO7+$m7+$mO$OQPO'#D_O/mQPO1G/SOOQO7+$V7+$VOOQO7+$^7+$^OOQO7+$a7+$aOOQO7+$d7+$dOOQO7+$g7+$gOOQO7+$i7+$iOOQO7+$k7+$kO0hQPO'#DTOOQO,59m,59mO0mQPO,59mOOQO,59T,59TOOQO,59y,59yOOQO-E7]-E7]O0uQPO,59oO1^QPO'#DaO1fQPO1G/XOOQO1G/X1G/XO1nQPO'#DVOOQO'#DU'#DUOOQO1G/Z1G/ZOOQO,59{,59{OOQO-E7_-E7_OOQO7+$s7+$sOOQO,59q,59qO1uQPO,59qO0uQPO'#D`O1}QPO1G/]OOQO1G/]1G/]OOQO,59z,59zOOQO-E7^-E7^OOQO7+$w7+$w",
  stateData: "2Z~O!WOS~OSPOTVOYWOaXOdYOgZOj[Ol]On^Ot_O!XTO~OZ`O~OqaOSVXTVXYVXaVXdVXgVXjVXlVXnVXtVX!UVX!XVX~OUdO~OZeO~OZfO~OZgO~OZhO~OZiO~OZjO~OZkO~OZlO~OSmO~OSPOYWOaXOdYOgZOj[Ol]On^O~OSoO~OSqO~OSsO~OSuO~OSwO~OSxO~OSyO~OvzOSsaTsaYsaasadsagsajsalsansatsa!Usa!Xsa~O^|OSoiToiYoiaoidoigoijoiloinoiqoitoi!Uoi!Xoiroi~Or!OOSpaTpaYpaapadpagpajpalpanpatpa!Upa!Xpa~O^|OSXiTXiYXiaXidXigXijXilXinXiqXitXi!UXi!XXirXi~O^|OS`iT`iY`ia`id`ig`ij`il`in`iq`it`i!U`i!X`ir`i~O^|OSciTciYciacidcigcijcilcinciqcitci!Uci!Xcirci~O^|OSfiTfiYfiafidfigfijfilfinfiqfitfi!Ufi!Xfirfi~O^|OSiiTiiYiiaiidiigiijiiliiniiqiitii!Uii!Xiirii~O^|OSkiTkiYkiakidkigkijkilkinkiqkitki!Uki!Xkirki~O^|OSmiTmiYmiamidmigmijmilminmiqmitmi!Umi!Xmirmi~OS!XOU!XO!P!YO~O_![O~Or!OOSpiTpiYpiapidpigpijpilpinpitpi!Upi!Xpi~OZ!_O~Or!`O!P!bO~OU!dO_!dOvzOz!cO|!dO}!dO!O!dO~OS!XOU!XO~Or!`O!P!hO~O{!iO~P0uOr!kO{!mO~Or!kO{!pO~Oq!WS~",
  goto: "$i!UPP!V!ZPPP!Z!_!iPP!o!rPP!iP#[!iP#_!iP#b!iP!iP!iP!i#ePP!ZP#hP#p#v#kPPPPPP$P$V$]$cTTOUTSOUSROUQnaR!]!OXQOUa!ORpeQ}mQ!QpQ!RrQ!StQ!TvQ!UwQ!VxR!WyRrfRtgRvhRbRQ{lV!d!_!c!kQ!ZzR!f!`Q!e!_Q!j!cR!n!kQUORcUQ!PnR!^!PQ!l!jR!o!lQ!a!ZR!g!a",
  nodeNames: "⚠ Program Statement SliceStatement Identifier slice String NodeStatement ArtifactRef RmRef rmType Colon RmName Version At Number UiRef uiType UiName CmdRef cmdType CmdName EvtRef evtType EvtName ExcRef excType AutRef autType ExtRef extType GenericRef IncomingClause DependsArrow Comma DataStatement data JsonObject BraceL Property Value JsonArray BracketL BracketR true false null BraceR",
  maxTerm: 55,
  skippedNodes: [0],
  repeatNodeCount: 4,
  tokenData: "&^~RaXY!WYZ!c]^!cpq!Wrs!n|}$[!Q![$a![!]$z!^!_%P!b!c%[!c!}%a!}#O%x#P#Q%}#R#S%a#T#o%a#o#p&S#q#r&X~!]Q!W~XY!Wpq!W~!hQ!X~YZ!c]^!c~!qVOr!nrs#Ws#O!n#O#P#]#P;'S!n;'S;=`$U<%lO!n~#]OU~~#`RO;'S!n;'S;=`#i;=`O!n~#lWOr!nrs#Ws#O!n#O#P#]#P;'S!n;'S;=`$U;=`<%l!n<%lO!n~$XP;=`<%l!n~$aOr~~$fQ_~!O!P$l!Q![$a~$oP!Q![$r~$wP_~!Q![$r~%POZ~~%SP}!O%V~%[Oq~~%aO^~~%fUS~st%a}!O%a!Q![%a!c!}%a#R#S%a#T#o%a~%}Oz~~&SO{~~&XOv~~&^O!P~",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  specialized: [{term: 4, get: (value) => spec_Identifier[value] || -1}],
  tokenPrec: 789
})
