// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {labelContent} from "./tokens"
const spec_Identifier = {__proto__:null,slice:12, rm:20, ui:28, cmd:34, evt:40, exc:46, aut:50, ext:54, data:70, true:86, false:88, null:90}
export const parser = LRParser.deserialize({
  version: 14,
  states: ")xQVQQOOO}QQO'#CxOOQO'#Cd'#CdO!SQQO'#CyOOQO'#C_'#C_OOQO'#D]'#D]QVQQOOO!nQQO'#C`O!sQQO'#CeO!xQQO'#CiO!}QQO'#ClO#SQQO'#CoO#XQQO'#CrO#^QQO'#CtO#cQQO'#CvO#hQQO'#DOO#mQQO,59dO#rQQO,59eOOQO-E7Z-E7ZOOQO,58z,58zO$pQQO,59PO$uQQO,59TO$zQQO,59WO%PQQO,59ZO%UQQO,59^O%ZQQO,59`O%`QQO,59bO%eQQO,59jOOQO1G/O1G/OO%jQRO'#C{OOQO1G/P1G/POOQO'#Ch'#ChOOQO1G.k1G.kOOQO'#Ck'#CkOOQO1G.o1G.oOOQO'#Cn'#CnOOQO1G.r1G.rOOQO'#Cq'#CqOOQO1G.u1G.uOOQO1G.x1G.xOOQO1G.z1G.zOOQO1G.|1G.|O%rQQO'#DQOOQO1G/U1G/UOOQO,59g,59gO%}QQO,59gO&SQQO'#DSOOQO,59l,59lO&XQQO,59lOOQO1G/R1G/RO&aQQO,59nO&xQQO'#D_O'QQQO1G/WOOQO1G/W1G/WO'YQQO'#DVOOQO'#DT'#DTOOQO1G/Y1G/YOOQO,59y,59yOOQO-E7]-E7]OOQO7+$r7+$rOOQO,59q,59qO'aQQO,59qO&aQQO'#D^O'iQQO1G/]OOQO1G/]1G/]OOQO,59x,59xOOQO-E7[-E7[OOQO7+$w7+$w",
  stateData: "'u~O!UOS~OTPOUVOYWO^XOaYOdZOg[Oi]Ok^OnROs_O!VTO~OZ`O~OTPOYWO^XOaYOdZOg[Oi]Ok^O~OVcO~OZdO~OZeO~OZfO~OZgO~OZhO~OZiO~OZjO~OZkO~OTlO~OpmOTmaUmaYma^maamadmagmaimakmanmasma!Sma!Vma~OToO~OTqO~OTsO~OTuO~OTwO~OTxO~OTyO~OuzO~OP}Oq|O~OT!OOV!OO!O!PO~Oq!RO~OZ!SO~Oz!TO!O!VO~OV!XOp!WOuzOx!XO{!XO|!XO}!XO~OT!OOV!OO~Oz!TO!O!]O~Oq!^O~P&aOq!bOz!`O~Oq!eOz!`O~On!UT~",
  goto: "#n!SPPP!T!XPPP!X!]PP!d!]P!g!]P!j!]P!m!]P!]P!]P!]!XP!pPP!XP!sP!{#RP!vPPPPP#[#b#hTTOUTSOUSQOURaRRpdRreRtfRvgRnaQ{kV!X!S!W!`Q!QzR!Z!TQ!Y!SQ!_!WR!c!`QUORbUQ!a!_R!d!aQ!U!QR![!U",
  nodeNames: "⚠ LabelContent Program Statement SliceStatement Identifier slice String ArtifactStatement RmArtifact rmType Colon RmName UiArtifact uiType UiName CmdArtifact cmdType CmdName EvtArtifact evtType EvtName ExcArtifact excType AutArtifact autType ExtArtifact extType GenericArtifact ArrowStatement Arrow Label BracketL BracketR DataStatement data JsonObject BraceL Property Value Number JsonArray Comma true false null BraceR",
  maxTerm: 53,
  skippedNodes: [0],
  repeatNodeCount: 3,
  tokenData: "&U~R`XY!TYZ!`]^!`pq!Trs!k|}$X}!O$^!Q![$i![!]%S!c!}%X!}#O%p#P#Q%u#R#S%X#T#o%X#o#p%z#q#r&P~!YQ!U~XY!Tpq!T~!eQ!V~YZ!`]^!`~!nVOr!krs#Ts#O!k#O#P#Y#P;'S!k;'S;=`$R<%lO!k~#YOV~~#]RO;'S!k;'S;=`#f;=`O!k~#iWOr!krs#Ts#O!k#O#P#Y#P;'S!k;'S;=`$R;=`<%l!k<%lO!k~$UP;=`<%l!k~$^Oz~~$aP!`!a$d~$iOn~~$nQx~!O!P$t!Q![$i~$wP!Q![$z~%PPx~!Q![$z~%XOZ~~%^UT~st%X}!O%X!Q![%X!c!}%X#R#S%X#T#o%X~%uOp~~%zOq~~&POu~~&UO!O~",
  tokenizers: [labelContent, 0],
  topRules: {"Program":[0,2]},
  specialized: [{term: 5, get: (value) => spec_Identifier[value] || -1}],
  tokenPrec: 309
})
